### ISSUE TITLE
Mix of optional and required parameter validation

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#10]
There seems to be missing validation around supplied parameters. For example:
```
andrew$ node JmeterDataSummary.js --from 2017-03-01 --to 2017-03-31
You selected the date range of: 
From 2017-03-01
To 2017-03-31
with an index uri of: 
Retrieving data
  Retrieving [#-------------------] retrieved: 31000 | total: 941602 | % complete: 3% | time remaining: 2762.8s
```
But "index uri" is nothing - where's it going to end up?

**Comment by FallenMan13** [comment]
If the index uri is blank the user will be prompted to enter the destination when indexData is called. I'll change the message that is displayed based on what the user entered as parameters when running the program.

**Comment by FallenMan13** [comment]
Validation added to `startRequest` to check that both dates have been entered and that they are both numbers when parsed using `Date.parse()`, and to alert the user that the index uri will be prompted for later in the process if none is provided alongside valid dates

**Comment by goofballLogic** [comment]
looks good
