### ISSUE TITLE
Data source is hard coded to "jmeter-*"

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#11]
On https://github.com/FallenMan13/Data-summarization/blob/master/getPage.js#L9, the data being read is hardcoded. It would be better to allow someone to indicate another set of data they wish to index, with ```jmeter-*``` as the default

**Comment by FallenMan13** [comment]
The user is now asked if they would like to use the default data retrieval uri `jmeter-*` or if they would like to use a different uri that they will enter.

**Comment by goofballLogic** [comment]
there doesn't seem to be a matching parameter that i can supply.
I'm sorry to be picky, but usually these types of scripts have two main scenarios:
1. A user who doesn't know what they are doing and needs prompted for everything (which you've done)
2. A user who runs the command automatically, often as a part of a larger script that they have stored as a batch file, powershell script or bash script.

**Comment by FallenMan13** [comment]
Command line parameter added for source uri. If this is not supplied along with the start and end dates in the command line the user is made aware that they will be prompted to enter one at a later stage in the script.
