### ISSUE TITLE
Sloooooow?

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#12]
If I want an index for e.g. 1 month's worth of data, the process seems to take a long time.
For example:
```
You selected the date range of: 
From 2017-03-01
To 2017-03-31
with an index uri of: 
Retrieving data
  Retrieving [###-----------------] retrieved: 147000 | total: 941602 | % complete: 16% | time remaining: 3205.7s
```
So that means the total time take is going to be ~1h3m.
I note that there's a potentially faster mechanism supported: https://www.elastic.co/guide/en/elasticsearch/guide/1.x/scan-scroll.html

Can that be implemented to speed things up?

**Comment by FallenMan13** [comment]
When I attempt to use the scan and scroll method for retrieving the data I get this error
```
Got an error:  {
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No search type for [scan]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No search type for [scan]"
  },
  "status": 400
}
```
I think that method might be for an older version of elasticsearch.

**Comment by goofballLogic** [comment]
Ah, I believe you are correct. Perhaps it would be good to try altering the page sizes. You could make that a parameter too.

Another alternative would be to do the aggregation in Elasticsearch, instead of doing it within your script (the stuff you've been doing in ```analyzeAnswer```). That way you don't need to download all that stuff from Elasticsearch at all. 

An example can be found here: https://blog.madewithlove.be/post/elasticsearch-aggregations/
