### ISSUE TITLE
ability to supply dates and destination index as command-line parameters

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#7]
I would like to be able to execute the script using a command like this:

```
node JmeterDataSummary.js --from 2017-03-01 --to 2017-03-31 --index http://10.156.24.35:5601/march-data-summary
```
So that I don't have to use the interactive UI.

This is a "feature request" (not a bug) - but I don't have permission to add a Label to this issue.

**Comment by FallenMan13** [comment]
It should now be possible to enter parameters for the script through the command line, allowing the user to bypass the interactive interface completely.

**Comment by goofballLogic** [comment]
ok, it's normal to prompt the user about command line parameter possibilities if they run without it. Modules like https://www.npmjs.com/package/commander can help do this without too much coding.

**Comment by FallenMan13** [comment]
The user is now made aware of the command line parameters if none are entered, along with an example demonstrating how to use them.
