### ISSUE TITLE
Progress reporting?

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#8]
Not sure if this is possible, but it would be nice to know ahead of time how much longer I need to wait.
e.g. I ran:
```node JmeterDataSummary.js --from 2017-03-01 --to 2017-03-31```
and the thing just sat there logging until i stopped it. Not sure how far through i was...
```
andrew@bfs-spare-1:~/src/Data-summarization$ node JmeterDataSummary.js --from 2017-03-01 --to 2017-03-31
Retrieving first page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
Got 1000 results
Retrieving next page
^C

```

**Comment by FallenMan13** [comment]
resultHandling now displays the total number of results for the request compared against a running total of collected results.

**Comment by FallenMan13** [comment]
Static progress bar added to resultHandling, package.json file updated to include new dependency and getPage changed to only output "Retrieving data" to prevent the progress bar from being forced to duplicate, all added to Edited-dataSummary branch. Progress bar displays a total of the results retrieved so far, the total number of results to retrieve and the percentage of the request that is complete.

**Comment by goofballLogic** [comment]
ok it seems to be flashing in a weird way. I'll have a shufti at the code

**Comment by goofballLogic** [comment]
Looking at the code, I note the following problems:
1. you are storing the current position in a module-scoped variable "currpos", then recreating a new progress bar for every call to ```handleResults```. Why not just create a progress bar on the first call to ```handleResults``` and store that at the module-scope

For example:
```
var currbar = null;
module.exports.handleResults = function handleSearchResults(error, response, body){ // Function to push data collected from the request into an array
  if(error || response.statusCode != 200){ // If an error was encountered, or if the response code recieved was not 200 OK
    console.log("Got an error: ", JSON.stringify(body, null, 2)); // Stringify the body of the response and output it to the console
    return;
  }
  var res = body.hits.hits;
  if (!currbar) {
     currbar = new ProgressBar('  Retrieving [:bar] retrived: :current | total: ' + body.hits.total + ' | % complete: :percent | time remaining: :etas', {
      complete: '#'
    , incomplete: '-'
    , width: 20
    , total: body.hits.total
     });
  }
```

2. It appears that you are using ```bar.tick``` (called 1000 times in a row!) rather than just updating the total directly. While this makes for an entertaining display, it's perhaps not the most efficient approach?

**Comment by FallenMan13** [comment]
Progress bar created once upon first call to `handeResults` and no longer ticks once per cycle in the `forEach` i.e. no more 1000 ticks per page retrieval and no more flashing progress bar.

**Comment by goofballLogic** [comment]
Looks good
